import { Hospital, Doctor, Staff, Token } from './types';

export const hospitals: Hospital[] = [
  {
    id: 'h1',
    name: "Aga Khan University Hospital",
    type: 'Private Hospital',
    category: 'Private',
    city: 'Karachi',
    area: 'Stadium Road',
    rating: 4.9,
    reviewsCount: 5000,
    specializations: ['Cardiology', 'Neurology', 'Oncology', 'Pediatrics'],
    facilities: ['Emergency', 'ICU', 'Modern Lab', 'Pharmacy', 'Ambulance', 'Air Ambulance'],
    insurancePanels: ['Jubilee', 'State Life', 'Adamjee'],
    startingFee: 3500,
    emergencyFee: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1586773860418-d3b9a8ec81c2?auto=format&fit=crop&q=80&w=800',
    verified: true,
    isOpen: true,
    address: 'National Stadium Rd, Aga Khan University Hospital, Karachi, Pakistan',
    phone: '+92 21 111 911 911',
    whatsapp: '+92 300 8222911',
    emergencyContact: '+92 21 34930051',
    about: "Aga Khan University Hospital is a premier healthcare institution providing international standard medical care in Pakistan since 1985.",
    openingTime: '00:00',
    closingTime: '23:59',
    openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    hasEmergency247: true,
    isApproved: true,
    isSuspended: false,
    staffStats: {
      doctors: 500,
      nurses: 1200,
      admin: 300,
      support: 800
    }
  },
  {
    id: 'h2',
    name: "Jinnah Postgraduate Medical Centre",
    type: 'Government Hospital',
    category: 'Government',
    city: 'Karachi',
    area: 'Cantt',
    rating: 4.4,
    reviewsCount: 8500,
    specializations: ['Emergency', 'Surgery', 'Maternity', 'Orthopedic'],
    facilities: ['24/7 Emergency', 'OPD', 'Blood Bank', 'Pharmacy', 'Vaccination'],
    insurancePanels: ['Sehat Card'],
    startingFee: 0,
    emergencyFee: 0,
    imageUrl: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800',
    verified: true,
    isOpen: true,
    address: 'Rafiqui Shaheed Road, Karachi Cantt, Karachi, Pakistan',
    phone: '+92 21 99201300',
    whatsapp: '+92 311 0000000',
    emergencyContact: '+92 21 1122',
    about: 'Jinnah Hospital is one of the largest and oldest public sector hospitals in Pakistan, serving thousands of patients daily.',
    openingTime: '00:00',
    closingTime: '23:59',
    openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    hasEmergency247: true,
    isApproved: true,
    isSuspended: false,
    staffStats: {
      doctors: 800,
      nurses: 1500,
      admin: 400,
      support: 1000
    }
  },
  {
    id: 'h3',
    name: "Liaquat National Hospital",
    type: 'Private Hospital',
    category: 'Private',
    city: 'Karachi',
    area: 'Gulshan-e-Iqbal',
    rating: 4.7,
    reviewsCount: 3200,
    specializations: ['Gastroenterology', 'Dermatology', 'Urology'],
    facilities: ['Emergency', 'Diagnostic Center', 'Physiotherapy', 'Ambulance'],
    insurancePanels: ['Efu Life', 'TPL Insurance'],
    startingFee: 2500,
    emergencyFee: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1587350859739-165039df899f?auto=format&fit=crop&q=80&w=800',
    verified: true,
    isOpen: true,
    address: 'National Stadium Rd, Gulshan-e-Iqbal, Karachi, Pakistan',
    phone: '+92 21 111 456 456',
    whatsapp: '+92 333 1234567',
    emergencyContact: '+92 21 34412000',
    about: 'Liaquat National Hospital is a leading non-profit health care provider and a center of excellence in medical education.',
    openingTime: '00:00',
    closingTime: '23:59',
    openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    hasEmergency247: true,
    isApproved: true,
    isSuspended: false,
    staffStats: {
      doctors: 350,
      nurses: 800,
      admin: 150,
      support: 500
    }
  },
  {
    id: 'h4',
    name: "South City Hospital",
    type: 'Private Hospital',
    category: 'Private',
    city: 'Karachi',
    area: 'Clifton',
    rating: 4.8,
    reviewsCount: 1500,
    specializations: ['Orthopedics', 'Plastic Surgery', 'ENT'],
    facilities: ['Boutique Rooms', 'Specialized Surgery', 'Pharmacy'],
    insurancePanels: ['Allied Insurance'],
    startingFee: 4000,
    emergencyFee: 6000,
    imageUrl: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800',
    verified: true,
    isOpen: true,
    address: 'St-1, Block 3, Shahrah-e-Firdousi, Clifton, Karachi, Pakistan',
    phone: '+92 21 111 724 000',
    whatsapp: '+92 345 8222724',
    emergencyContact: '+92 21 35832724',
    about: 'South City Hospital provides luxury healthcare services with state-of-the-art surgical facilities.',
    openingTime: '00:00',
    closingTime: '23:59',
    openDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'],
    hasEmergency247: true,
    isApproved: true,
    isSuspended: false,
    staffStats: {
      doctors: 100,
      nurses: 300,
      admin: 80,
      support: 120
    }
  }
];

export const doctors: Doctor[] = [
  {
    id: 'd1',
    hospitalId: 'h1',
    name: 'Dr. Abdul Bari',
    specialization: 'Cardiology',
    qualifications: ['MBBS', 'MD', 'FCPS (Cardiology)'],
    fee: 3500,
    availableToday: true,
    nextSlot: '11:00 AM',
    imageUrl: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=200',
    verified: true,
    title: 'Professor of Cardiology'
  },
  {
    id: 'd2',
    hospitalId: 'h1',
    name: 'Dr. Farhat Abbas',
    specialization: 'Neurology',
    qualifications: ['MBBS', 'FRCP', 'PhD'],
    fee: 4000,
    availableToday: true,
    nextSlot: '03:30 PM',
    imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=200',
    verified: true,
    title: 'Consultant Neurologist'
  }
];

export const staffMembers: Staff[] = [
  {
    id: 's1',
    hospitalId: 'h1',
    name: 'Asim Raza',
    cnic: '42101-1234567-1',
    role: 'Nursing Supervisor',
    department: 'Nursing',
    shift: 'Morning',
    status: 'PRESENT',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCDNJ5jSjY5ABhhhC-7lCABPxGKPV4CSGyuti1dAHc3MlA5DwDvoG-JV4rPJcBhD5jal_0S6JYM5l2MylYA78azLsyW6HYBzkNTpyQFRJ5xAjySrY-6Ce9niIqAPQDAA6usMbSAaDZzvMVLeBFl_zgXyG74JRwB_WPu819WD1NkZfRgaTwIKTjZiwZ7pgQJ9JYx45WyriJJxbU2rRz-bK510ezO9MdklDLq5yM6qzvfm_nOxljyJRr8WsEgMydn3uilxOXmgGgG5Nk',
    joiningDate: '2022-01-15',
    phone: '+92 300 0000001'
  },
  {
    id: 's2',
    hospitalId: 'h1',
    name: 'Fatima Malik',
    cnic: '42101-7654321-2',
    role: 'Admin Officer',
    department: 'Admin',
    shift: 'Morning',
    status: 'PRESENT',
    imageUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCnUMLmt6oBrCoQa6H_hMlCHK6Ik45dOqWQ2Y62CcCwIbp11xZoikIl4iwPZCQYzS9uAqqsFxD-abqMO6dnF3iWPp5KePhcCdRvWJyJctEWUiR-3v5PyebrpAl7wpkbMxCU4cj4Mp2sevGcBJIaXE-o-qwEzUYr1YtLBZlc1PlyembP0arRWToK0StPHl6NCw95gFQgONO430SsmIG1XJl7bRLZmDWTdL-RydD5yx_YhWaZ3Jb_F0Js7Dm-iiPiRZHFmYjUdlDdGo4',
    joiningDate: '2023-05-20',
    phone: '+92 321 9999999'
  }
];

export const queueTokens: Token[] = [
  {
    id: 't1',
    hospitalId: 'h1',
    number: 'A-43',
    patientName: 'Ahmed Khan',
    patientPhone: '+92 300 9876543',
    doctorName: 'Dr. James Wilson',
    timeSlot: '10:45 AM',
    status: 'Waiting',
    createdAt: '2023-10-24T09:00:00Z',
    fee: 2500,
    paymentMethod: 'Cash'
  },
  {
    id: 't2',
    hospitalId: 'h1',
    number: 'A-44',
    patientName: 'Sara Ahmed',
    patientPhone: '+92 333 1112223',
    doctorName: 'Dr. James Wilson',
    timeSlot: '10:50 AM',
    status: 'Emergency',
    isEmergency: true,
    createdAt: '2023-10-24T09:15:00Z',
    fee: 3500,
    paymentMethod: 'JazzCash'
  }
];
